version: '3.7'

services:
  hr-buddy-server:
    build: ./hr-buddy-server
    ports:
      - 8080:8080

  hr-buddy-ui:
    build: ./hr-buddy-ui
    ports:
      - 80:80
    depends_on:
      - hr-buddy-server
    environment:
      SERVER_URL: http://hr-buddy-server:8080
